import React, { useState, useCallback } from 'react'
import { CodeMap } from '@models/codeMap'

type OutputFormat = 'json' | 'markdown' | 'yaml' | 'html'

interface ReportGeneratorProps {
  codeMap: CodeMap
  healthScore?: { grade: string; score: number }
  issues?: Array<{ type: string; title: string; count: number; description: string }>
}

export const ReportGenerator: React.FC<ReportGeneratorProps> = ({ codeMap, healthScore, issues }) => {
  const [selectedFormat, setSelectedFormat] = useState<OutputFormat>('markdown')
  const [generating, setGenerating] = useState(false)

  const generateReport = useCallback(() => {
    const nodes = codeMap.getNodes()
    const edges = codeMap.getEdges()
    const files = codeMap.getFiles()

    // Gather statistics
    const stats = {
      totalFiles: files.length,
      totalNodes: nodes.length,
      totalEdges: edges.length,
      totalLines: nodes.reduce((sum, n) => sum + (n.data.metrics?.linesOfCode || 0), 0),
      avgComplexity:
        nodes.length > 0
          ? (nodes.reduce((sum, n) => sum + (n.data.metrics?.cyclomatic || 0), 0) / nodes.length).toFixed(2)
          : 0,
      nodesByType: nodes.reduce((acc, n) => {
        acc[n.data.type] = (acc[n.data.type] || 0) + 1
        return acc
      }, {} as Record<string, number>),
      edgesByType: edges.reduce((acc, e) => {
        acc[e.data.type] = (acc[e.data.type] || 0) + 1
        return acc
      }, {} as Record<string, number>),
    }

    const reportData = {
      meta: {
        generated: new Date().toISOString(),
        tool: 'Code Cartographer v2.0',
        rootPath: codeMap.root,
      },
      summary: {
        healthGrade: healthScore?.grade || 'N/A',
        healthScore: healthScore?.score || 0,
        ...stats,
      },
      issues: issues || [],
      details: {
        files: files.map((f) => ({
          path: f.data.path,
          language: f.data.language,
          nodes: nodes.filter((n) => n.data.file === f.data.path).map((n) => ({
            name: n.data.name,
            type: n.data.type,
            lines: n.data.metrics?.linesOfCode,
            complexity: n.data.metrics?.cyclomatic,
          })),
        })),
      },
    }

    return reportData
  }, [codeMap, healthScore, issues])

  const formatAsJSON = useCallback((data: any) => {
    return JSON.stringify(data, null, 2)
  }, [])

  const formatAsMarkdown = useCallback((data: any) => {
    const lines: string[] = []
    lines.push('# Code Analysis Report')
    lines.push('')
    lines.push(`Generated: ${data.meta.generated}`)
    lines.push(`Tool: ${data.meta.tool}`)
    lines.push('')
    lines.push('## Summary')
    lines.push('')
    lines.push(`| Metric | Value |`)
    lines.push(`|--------|-------|`)
    lines.push(`| Health Grade | **${data.summary.healthGrade}** |`)
    lines.push(`| Health Score | ${data.summary.healthScore}/100 |`)
    lines.push(`| Total Files | ${data.summary.totalFiles} |`)
    lines.push(`| Total Functions/Classes | ${data.summary.totalNodes} |`)
    lines.push(`| Total Connections | ${data.summary.totalEdges} |`)
    lines.push(`| Total Lines of Code | ${data.summary.totalLines} |`)
    lines.push(`| Average Complexity | ${data.summary.avgComplexity} |`)
    lines.push('')

    if (data.issues.length > 0) {
      lines.push('## Issues')
      lines.push('')
      data.issues.forEach((issue: any) => {
        const icon = issue.type === 'error' ? '🔴' : issue.type === 'warning' ? '🟡' : '🔵'
        lines.push(`### ${icon} ${issue.title} (${issue.count} items)`)
        lines.push('')
        lines.push(issue.description)
        lines.push('')
      })
    }

    lines.push('## Node Types')
    lines.push('')
    Object.entries(data.summary.nodesByType).forEach(([type, count]) => {
      lines.push(`- **${type}**: ${count}`)
    })
    lines.push('')

    lines.push('## Connection Types')
    lines.push('')
    Object.entries(data.summary.edgesByType).forEach(([type, count]) => {
      lines.push(`- **${type}**: ${count}`)
    })
    lines.push('')

    lines.push('---')
    lines.push('*Generated by Code Cartographer*')

    return lines.join('\n')
  }, [])

  const formatAsYAML = useCallback((data: any) => {
    const toYAML = (obj: any, indent = 0): string => {
      const spaces = '  '.repeat(indent)
      let result = ''

      for (const [key, value] of Object.entries(obj)) {
        if (value === null || value === undefined) {
          result += `${spaces}${key}: null\n`
        } else if (Array.isArray(value)) {
          result += `${spaces}${key}:\n`
          value.forEach((item) => {
            if (typeof item === 'object') {
              result += `${spaces}  -\n${toYAML(item, indent + 2)}`
            } else {
              result += `${spaces}  - ${item}\n`
            }
          })
        } else if (typeof value === 'object') {
          result += `${spaces}${key}:\n${toYAML(value, indent + 1)}`
        } else {
          result += `${spaces}${key}: ${value}\n`
        }
      }

      return result
    }

    return toYAML(data)
  }, [])

  const formatAsHTML = useCallback((data: any) => {
    return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Code Analysis Report</title>
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; max-width: 900px; margin: 0 auto; padding: 2rem; background: #1f2937; color: #f3f4f6; }
    h1 { color: #60a5fa; border-bottom: 2px solid #3b82f6; padding-bottom: 0.5rem; }
    h2 { color: #a78bfa; margin-top: 2rem; }
    table { width: 100%; border-collapse: collapse; margin: 1rem 0; }
    th, td { padding: 0.75rem; text-align: left; border-bottom: 1px solid #374151; }
    th { background: #111827; font-weight: 600; }
    .grade { font-size: 2rem; font-weight: bold; color: #10b981; }
    .issue { padding: 1rem; margin: 0.5rem 0; border-radius: 8px; border-left: 4px solid; }
    .issue.error { background: #7f1d1d33; border-color: #ef4444; }
    .issue.warning { background: #78350f33; border-color: #f59e0b; }
    .issue.info { background: #1e3a5f33; border-color: #3b82f6; }
    .badge { display: inline-block; padding: 0.25rem 0.5rem; border-radius: 4px; font-size: 0.75rem; font-weight: 600; }
    .badge.error { background: #7f1d1d; color: #fecaca; }
    .badge.warning { background: #78350f; color: #fef3c7; }
    footer { margin-top: 3rem; padding-top: 1rem; border-top: 1px solid #374151; color: #6b7280; font-size: 0.875rem; }
  </style>
</head>
<body>
  <h1>Code Analysis Report</h1>
  <p>Generated: ${data.meta.generated}</p>

  <h2>Summary</h2>
  <p class="grade">${data.summary.healthGrade}</p>
  <table>
    <tr><th>Metric</th><th>Value</th></tr>
    <tr><td>Health Score</td><td>${data.summary.healthScore}/100</td></tr>
    <tr><td>Total Files</td><td>${data.summary.totalFiles}</td></tr>
    <tr><td>Total Functions/Classes</td><td>${data.summary.totalNodes}</td></tr>
    <tr><td>Total Connections</td><td>${data.summary.totalEdges}</td></tr>
    <tr><td>Lines of Code</td><td>${data.summary.totalLines}</td></tr>
    <tr><td>Avg Complexity</td><td>${data.summary.avgComplexity}</td></tr>
  </table>

  ${
    data.issues.length > 0
      ? `<h2>Issues</h2>${data.issues
          .map(
            (i: any) =>
              `<div class="issue ${i.type}"><span class="badge ${i.type}">${i.type.toUpperCase()}</span> <strong>${i.title}</strong> (${i.count} items)<br/>${i.description}</div>`
          )
          .join('')}`
      : ''
  }

  <h2>Node Distribution</h2>
  <table>
    <tr><th>Type</th><th>Count</th></tr>
    ${Object.entries(data.summary.nodesByType)
      .map(([type, count]) => `<tr><td>${type}</td><td>${count}</td></tr>`)
      .join('')}
  </table>

  <footer>Generated by Code Cartographer v2.0</footer>
</body>
</html>`
  }, [])

  const handleExport = useCallback(() => {
    setGenerating(true)

    try {
      const data = generateReport()
      let content: string
      let mimeType: string
      let extension: string

      switch (selectedFormat) {
        case 'json':
          content = formatAsJSON(data)
          mimeType = 'application/json'
          extension = 'json'
          break
        case 'markdown':
          content = formatAsMarkdown(data)
          mimeType = 'text/markdown'
          extension = 'md'
          break
        case 'yaml':
          content = formatAsYAML(data)
          mimeType = 'text/yaml'
          extension = 'yaml'
          break
        case 'html':
          content = formatAsHTML(data)
          mimeType = 'text/html'
          extension = 'html'
          break
        default:
          content = formatAsJSON(data)
          mimeType = 'application/json'
          extension = 'json'
      }

      const blob = new Blob([content], { type: mimeType })
      const url = URL.createObjectURL(blob)
      const link = document.createElement('a')
      link.download = `code-analysis-report-${Date.now()}.${extension}`
      link.href = url
      link.click()
      URL.revokeObjectURL(url)
    } catch (error) {
      console.error('Export failed:', error)
    } finally {
      setGenerating(false)
    }
  }, [selectedFormat, generateReport, formatAsJSON, formatAsMarkdown, formatAsYAML, formatAsHTML])

  const handleCopyToClipboard = useCallback(async () => {
    try {
      const data = generateReport()
      let content: string

      switch (selectedFormat) {
        case 'json':
          content = formatAsJSON(data)
          break
        case 'markdown':
          content = formatAsMarkdown(data)
          break
        case 'yaml':
          content = formatAsYAML(data)
          break
        case 'html':
          content = formatAsHTML(data)
          break
        default:
          content = formatAsJSON(data)
      }

      await navigator.clipboard.writeText(content)
    } catch (error) {
      console.error('Copy failed:', error)
    }
  }, [selectedFormat, generateReport, formatAsJSON, formatAsMarkdown, formatAsYAML, formatAsHTML])

  return (
    <div className="report-generator">
      <div className="report-header">
        <h4>Export Report</h4>
      </div>

      <div className="report-controls">
        <select
          className="format-select"
          value={selectedFormat}
          onChange={(e) => setSelectedFormat(e.target.value as OutputFormat)}
        >
          <option value="markdown">Markdown (.md)</option>
          <option value="json">JSON (.json)</option>
          <option value="yaml">YAML (.yaml)</option>
          <option value="html">HTML Report (.html)</option>
        </select>

        <div className="report-buttons">
          <button className="report-btn" onClick={handleCopyToClipboard} title="Copy to clipboard">
            <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
              <rect x="9" y="9" width="13" height="13" rx="2" ry="2" />
              <path d="M5 15H4a2 2 0 01-2-2V4a2 2 0 012-2h9a2 2 0 012 2v1" />
            </svg>
          </button>
          <button className="report-btn primary" onClick={handleExport} disabled={generating}>
            {generating ? (
              <span className="export-spinner"></span>
            ) : (
              <>
                <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                  <path d="M21 15v4a2 2 0 01-2 2H5a2 2 0 01-2-2v-4M7 10l5 5 5-5M12 15V3" />
                </svg>
                Export
              </>
            )}
          </button>
        </div>
      </div>

      <div className="format-description">
        {selectedFormat === 'markdown' && 'Human-readable documentation format'}
        {selectedFormat === 'json' && 'Machine-readable data format'}
        {selectedFormat === 'yaml' && 'Configuration-friendly format'}
        {selectedFormat === 'html' && 'Standalone HTML report with styling'}
      </div>
    </div>
  )
}
